### ISSUE TITLE
JB Duke hotel information issues and improvements

### ISSUE THREAD

**Issue by aviggio** [vivoconference/vivoconference.github.io#23]
Community feedback:

> I tried to follow the advice I was writing in VIVO Updates to stay at the JB Duke.  I couldn't see how to do it.  The registration site refers one back to the main page of the VIVO Conference site.  No info there about the JB Duke or how to Stay There.  There is an imbedded link to the JB Duke, and if you click it, you'll be take to a Book Now page.  I didn't find this the first or second time I visited the registration site.  Can you please make the registration site clearer.  It should say: "To book a room at the JB Duke, click here.  And remove the sentence that says "for more info …"  There is no more info on the conference web site.  If there is, please take the user directly to it, rather than to the conference home page.
> 
> I recommend the "Attend Page" title should be changed.  Rather than "Hotels" It should say "Hotel"
> 
> Also on Attend, rather than Conference Venue, the first panel should say "Conference Hotel".  Lead them straight to the JB Duke.
> 
> Also in the Conference Venue panel, the link to the JB Duke goes to the generic hotel web site.  It should go to the Book Now link.  Lead them straight to the JB Duke.
> 
> The Lunch and Dinner page should be called "Lunch and Dinner" (not Nearby Restaurants) Don't lead them away from the hotel.  Lead them to the hotel.
> 
> The first item on the Lunch and Dinner page should be an explanation of Lunch and Dinner at the JB Duke.  It's unusual and it needs to be front, center, and recommended.
> 
> Same comment for the conference web site.  No obvious info on the JB Duke.  Rather than "Durham NC, It should say "JB Duke Hotel, Durham NC"  Lead them to the JB Duke.
> 
> The site looks beautiful.  It needs to be wayfinding for the hotel.

**Comment by mconlon17** [comment]
Registration page at EventBrite was improved by Violeta.

**Comment by aviggio** [comment]
@mconlon17 made most of these changes taking into account some feedback from Julia via email (screenshot not attached here).

Will check back with Julia for ideas on text for the Lunch and Dinner page, but edited it to remove the references to take people away from JB Duke.
