### ISSUE TITLE
Update Things To Do

### ISSUE THREAD

**Issue by mconlon17** [vivoconference/vivoconference.github.io#25]
The NYC content needs to be replaced with Durham content (perhaps minimal).  Might recommend adding a sentence like "before or after the conference, visit ..."  (Again emphasizing that the conference time should be spent on site at the JB Duke)

**Comment by aviggio** [comment]
Damaris Murry shared this content for the Things To Do page. Feel free to make suggestions. 

https://docs.google.com/document/d/15A8Ou6DdYIQmCFDd9wpNl8O4TBGmB0Q3D_iqQvxzZ1k/edit
