### ISSUE TITLE
add info and photos of 2 invited speakers

### ISSUE THREAD

**Issue by vioil** [vivoconference/vivoconference.github.io#67]
Can you please plan on adding the information about VIVO 2019 invited Speakers?

Here is the information: https://docs.google.com/document/d/1BG4jy7mUmmZyk--HqYEphq4BKPAfN5XLBH1JXe0wCA0/edit#

**Comment by aviggio** [comment]
Hi @vioil to confirm you're requesting a new page be added for invited speakers, and not to update the existing page for keynotes at http://vivoconference.org/news/keynotes

Also to confirm there are no updates needed to that keynote page at this time?

**Comment by vioil** [comment]
yes, new post for the invited speakers and no changes to the keynote speaker news item.
